schema_version: v0.0.1

application:
  name: app-runner
  description: Journal app
  appConfig:
    version: 1
  artifacts:
    - name: AppRunnerSampleContainerImage
      id: 4FE1056C-E64F-46A3-8CA3-312AA19DE732
      containerImage:
        provider: public_elastic_container_registry
        repo: public.ecr.aws/t8r3g5k5/codepipes-diary-reference
        reference: latest
  creds:
    - cloud
    - git